# coding: utf-8

"""
    SeerNet Audio APIs

    OpenAPI Specification of SeerNet audio APIs

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import deepaffects
from deepaffects.rest import ApiException
from deepaffects.apis.emotion_api import EmotionApi


class TestEmotionApi(unittest.TestCase):
    """ EmotionApi unit test stubs """

    def setUp(self):
        self.api = deepaffects.apis.emotion_api.EmotionApi()

    def tearDown(self):
        pass

    def test_recognise_emotion(self):
        """
        Test case for recognise_emotion

        Find emotion in an audio file
        """
        pass


if __name__ == '__main__':
    unittest.main()
