# coding: utf-8

"""
    SeerNet Audio APIs

    OpenAPI Specification of SeerNet audio APIs

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import deepaffects
from deepaffects.rest import ApiException
from deepaffects.apis.denoise_api import DenoiseApi


class TestDenoiseApi(unittest.TestCase):
    """ DenoiseApi unit test stubs """

    def setUp(self):
        self.api = deepaffects.apis.denoise_api.DenoiseApi()

    def tearDown(self):
        pass

    def test_denoise_audio(self):
        """
        Test case for denoise_audio

        Denoise an audio file
        """
        pass


if __name__ == '__main__':
    unittest.main()
