# coding: utf-8

"""
    DeepAffects

    OpenAPI Specification of DeepAffects APIs

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.async_response import AsyncResponse
from .models.audio import Audio
from .models.diarize_audio import DiarizeAudio
from .models.emotion_score import EmotionScore
from .models.diarize_segment import DiarizeSegment

# import apis into sdk package
from .apis.denoise_api import DenoiseApi
from .apis.diarize_api import DiarizeApi
from .apis.emotion_api import EmotionApi
from .apis.featurize_api import FeaturizeApi
from .apis.ellipsis_api import EllipsisAPI
from .apis.diarize_api_v2 import DiarizeApiV2

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
