# coding: utf-8

"""
    DeepAffects

    OpenAPI Specification of DeepAffects APIs

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .async_response import AsyncResponse
from .audio import Audio
from .diarize_audio import DiarizeAudio
from .emotion_score import EmotionScore
