# coding: utf-8

"""
    SeerNet Audio APIs

    OpenAPI Specification of SeerNet audio APIs

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .audio import Audio
from .diarize_audio import DiarizeAudio
from .emotion_score import EmotionScore
